# Generated by Django 4.2.5 on 2024-01-19 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 19, 42, 6, 654140, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='station',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год ввода в строй'),
        ),
    ]
